env:
 - GHCVER=7.0.4
 - GHCVER=7.2.2
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.3
 - GHCVER=7.10.1
 - GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-head ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/head/bin:$PATH

install:
 - cabal update
 - cabal install --depend
 - ghc --version

script:
 - cabal configure -v2
 - cabal build
 - cabal sdist
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
